config/routes.rb
Rails.application.routes.draw do
  root 'homes#home'
  get '/help', to: 'homes#help'
  get '/contact', to: 'homes#contact'
  resources :users
  resources :sessions, only:[:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :email_downcase
  VALID_EMAIL_REJEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_secure_password

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: true,
            format: { with: VALID_EMAIL_REJEX }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  private

    def email_downcase
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:sessions][:email])
    if user && user.authenticate(params[:sessions][:password])
      log_in user
      flash[:success] = "ログインしました"
      redirect_to user
    else
      flash.now[:danger] = "メールアドレスかパスワードが正しくありません"
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:edit, :update]
  before_action :correct_user, only:[:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])

  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "登録が完了しました！"
      log_in @user
      redirect_to @user
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to users_path
  end

  private

      def user_params
        params.require(:user).permit(:name, :email, :password,
              :password_confirmation)
      end

        #before_action

      def logged_in_user
        unless logged_in?
          flash[:danger] = "ログインが必要です"
          redirect_to new_session_path
        end
      end

      def correct_user
        @user = User.find(params[:id])
        unless current_user?(@user)
          flash[:danger] = "権限がありません"
          redirect_to root_url
        end
      end

      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #ログイン
  def log_in(user)
    session[:user_id] = user.id
  end

  #現在のユーザーをかえす
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

   #現在のログインユーザーならtrue
   def current_user?(user)
     user == current_user
   end

  #ログイン時true
  def logged_in?
    !current_user.nil?
  end

  #ログアウト
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size:80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://s.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/homes/contact.html.erb
<h1>お問い合わせ</h1>

app/views/homes/help.html.erb
<h1>ヘルプ</h1>

app/views/homes/home.html.erb
<div class="row">
  <div class="jumbotron jumbotron-extend">
    <h1>Family Appへようこそ</h1>
    <div class="center">
      <%= link_to "新規登録をする", new_user_path,
            class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
    <footer class="footer">
      <nav>
        <ul>
          <li><%= link_to "トップ", root_path %></li>
          <li><%= link_to "お問い合わせ", contact_path %></li>
          <li><%= link_to "ヘルプ", help_path %></li>
        </ul>
      </nav>
    </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Family App", root_path,  id: "logo"  %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "ログイン中：#{current_user.name}", current_user %></li>
          <li><%= link_to "家族一覧", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              メニュー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", current_user %></li>
              <li><%= link_to "ログアウト", session_path(:id), method: :delete,
                        data: { confirm: "ログアウトしますか？" }%></li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to "ログイン", new_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
      <div class="container">
        <%= yield %>
        <%= render "layouts/footer" %>
      </div>
  </body>
</html>

app/views/layouts/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div class="alert alert-warning">
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error-messages">
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages" %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary active" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:button_text, "更新する") %>
<h1>編集</h1>

<div class="row">
  <div class="col-md-6  col-md-offset-3">
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">画像変更</a>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<h1>家族一覧</h1>

    <ul class="users">
      <% @users.each do |user| %>
        <li>
          <%= gravatar_for(user) %>
          <%= link_to user.name, user %>
          <% if current_user.admin? %>
            <%= link_to "削除", user, method: :delete,
                  data: { confirm: "本当に削除しますか？" }%>
          <% end %>
        </li>
      <% end %>
    </ul>

app/views/users/new.html.erb
<% provide(:button_text, "登録") %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6  col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<h1>マイページ</h1>

<div class="row">
  <div class="col-md-4">
    <%= gravatar_for @user %>
    <%= @user.name %>
    <p class="link"><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  </div>

</div>